using_account="Using %s account"
could_not_find_login_url="Could not find login url"
checking_login_credential="Checking login  credentials..."
sign_in_btn_not_found="Sign in btn found"
you_are_not_login="You are not loged in"
login_url="Login url: %s"
fetching_login_page="Fetching login page"
next_url="Next url:%s"

form_not_found_pquery="Form %s not found by pquery"
pquery_failed="Pquery failed %s"

could_not_load_cookie_file="Could not load cookie file %s"
could_not_write_cookie_file="Could not write cookie file %s"
could_not_clear_cookie_file="Could not clear cookie file %s"
human_clear_cookies="Human is clearing cookie"

login_successful="Login successfull"
cant_continue_util_setup_complete="Canot continue to the next step till your account profile setup complete"
please_fix_this_problem_by_with_your_browser="Please fix this problem by log in with your browser"
login_requested_add_phone="Login requested you to add phone"
send_pin_login_post="Sending pin login post"
send_email_login_post="Sending email login post"
next_post_payload="next post payload"
enter_pin_code="Enter the 6-digit code: "
login_requested_challenge="Login request challenge"
please_open_device_to_get_pin_code="Please open your phone or email to get code"
cant_continue_with_provided_passwd="Canot continue login with provided password %s"
cant_continue_with_provided_email="Canot continue login with provided email %s"
send_passwd_login_post="Sending password login post"
continue_login_page="Continue login page"
could_not_write_file="Could not write file %s"
could_not_open_file="Could not open file %s"
write_file_success="Write file %s success"

#Paga
page_name_doesnt_have_form_object="Page doesnt have form named %s"
cant_continue_server_send_checkpoint="Cant continue login process, client receive checkpoint, please try to login with your browser"
# Human
human_doesnt_have_page="Human doesnt have page named %s"
human_start_browsing="Human start browsing this url:%s"
human_browsing_resp_code="Resp Code %s"

form_post_payload="Form post payload:%s"
form_start_post="Form start post this action url:%s"
form_post_resp_code="Resp Code %s"

cant_continue_next_step_because_prev_errors="Cant continue next step because of previous errors"
could_not_load_json_file="Couldnt load json file:%s"
could_not_write_json_file="Couldnt write json file:%s"
