from sqlalchemy import Column, Integer, String
from robots.datasource.models import Base

class Transcript(Base):
	__tablename__ = 'transcript'

	id=Column(Integer,primary_key=True)
	tocId=Column(String)
	lang=Column(String)
	country=Column(String)
	autoGenerated=Column(String)

	def __repr__(self):
		return f"<Transcript(tocId={self.tocId},lang={self.lang},country={self.country},autoGenerated={self.autoGenerated},)>"
